### ISSUE TITLE
ServiceProvider not Found

### ISSUE THREAD

**Issue by Hexaflexagon** [invisnik/laravel-steam-inventory#1]
Hello,

i installed this paket via composer and added this `Invisnik\LaravelSteamInventory\ServiceProvider::class` into the `app/config/app.php`

Error Code:
`FatalThrowableError in ProviderRepository.php line 146:
Class 'Invisnik\LaravelSteamInventory\ServiceProvider' not found`

**Comment by invisnik** [comment]
Fix ccdf704
